version: "2"

services:
  backend:
    build: ./backend
    environment:
      APP_PORT: "4000"
      APP_HOST: "localhost"
    ports: 
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "8000:80"