version: "2"

services:
  backend:
    build: ./backend
    environment:
      APP_PORT: "4000"
      APP_HOST: "localhost"
    ports: 
      - "3000:4000"
  frontend:
    build: 
      context: ./frontend
      args:
        BACKEND_PORT: "3000"
        BACKEND_HOST: "localhost"
    ports:
      - "8000:80"